---
http:
  host: 127.0.0.1
  port: 9000
  # basic-auth:
  #   username: "foo"
  #   password: "bar"
database:
  migrations: "/home/mcorbin/appclacks/api/dev/migrations"
  username: "appclacks"
  password: "appclacks"
  database: "appclacks"
  host: "127.0.0.1"
  port: 5432
  ssl-mode: disable
healthcheck:
  probers: 1
