name: publish docker image
on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --rm-dist
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow

      - name: Login to Appclacks Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build/Push image appclacks/server:latest
        shell: /usr/bin/bash {0}
        run: |
          docker build . -t appclacks/server:latest
          docker push       appclacks/server:latest
          # get tags of current commit
          tag=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
          if [ ! -z "$tag" ]; then
            echo "Tag name from git describe: $tag"
            docker tag  appclacks/server:latest appclacks/server:$tag
            docker push appclacks/server:$tag
          fi
